### ISSUE TITLE
Haddock drive

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#106]
The haddocks is the place where libraries win the battle of adoption.  We need concise, consistent commentary, but not dry.  The narrative should add up to "mathematics is easy in haskell, and haskell is awesome for math."

In general, I think a good starting place for a haddock comment is a link to the canonical wiki page.  But we can be original as well.

`stack build --test --haddock --ghc-options=-Werror --file-watch`

**Comment by tonyday567** [comment]
#78 subsumed here too.

**Comment by JamieBallingall** [comment]
By "canonical wiki page", do you mean the one on Wikipedia or the Wiki hosted on Github (which currently appears to redirect to the code)?

**Comment by tonyday567** [comment]
@JamieBallingall personally, I find the Wikipedia entries across a lot of the numhask topic range to be first class, and pretty battle-hardened definitions.

Soon, I'm going to go through each class and check the laws, have a read of the WIkis, and think about how to encapsulate the concepts in some haddocks.
