### ISSUE TITLE
deriving-via

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#11]
@Icelandjack

Not sure how to shove a `newtype Vec (n::Nat) a = Vec (V.Vector a)` through the deriving-via machinery.  See https://github.com/tonyday567/numhask/blob/via/src/NumHask/Rep.hs#L46

Am I going wrong in the newtype type, or in using (KnownNat n) as a constraint in the representable instance, or something else?

With derivingVia line uncommented:

```
 • No instance for (KnownNat yyy) arising from a use of ‘pure’
      Possible fix:
        add (KnownNat yyy) to the context of
          the type signature for:
            pure :: forall a. a -> Vec yyy a
          or the instance declaration

```

**Comment by LeanderK** [comment]
I am not sure why this is linked in the 0.3-release ticket. Does this mean, that we will require 8.6 for the 0.3 release?
I am okay with this decision and would happily refactor the instances to use `deriving via`, but I think we first have to agree to switch to 8.6.

**Comment by tonyday567** [comment]
I claim closing #79 with a heart as decisive agreement!

ghc-8.6 seems imminent, and 0.3 is a breaking change for the very small number of downstream libraries that numhask supports (ie all of mine), so let's break it and support >= 8.6.1.

But I don't really know what deriving via really means for the library.  Some sort of example refactor would be awesome to start the process off.
