### ISSUE TITLE
break dependency on protolude?

### ISSUE THREAD

**Issue by stites** [tonyday567/numhask#12]
I'm wondering if numhask's protolude dependency can be broken for a lighter-weight package.

**Comment by tonyday567** [comment]
It's certainly worth an experiment.  The main downside I see is losing NumHask.Prelude, and then a simple import such as:

```
import NumHask
```

gets you a world of hurt with operator clashes, and that's difficult to use with any prelude, so you end up saying:

```
import Prelude
       hiding (Bounded(..), Integral(..), Rep, Semiring(..), (*), (**),
               (+), (-), (/), (^), (^^), abs, acos, acosh, asin, asinh, atan,
               atan2, atanh, ceiling, cos, cosh, exp, floor, fromInteger,
               fromIntegral, infinity, isNaN, log, logBase, negate, pi, product,
               recip, round, sin, sinh, sqrt, sum, tan, tanh, toInteger, trans,
               zero)
```

Is there any way of being prelude agnostic?

I'm open to anything that allows:

```
1+1
```

Upside is dependencies get down to base + QuickCheck + tasty, and these last two can probably be usefully factored out of the library proper.

**Comment by stites** [comment]
I think the idea here would be that NumHask would be a prelude in itself (so the `import NumHask` would still be desirable, just without the protolude bells and whistles). This way if someone wants to merge numhask into another prelude, they would start from the same base.

w.r.t. QuickCheck and tasty: something I've also seen is splitting out the prelude into a `-prelude` and `-prelude-extras` with all of the testing modules / orphans. Maybe, in a similar fashion, numhask could include a `-protolude` variant?

**Comment by tonyday567** [comment]
#16 achieves this
