### ISSUE TITLE
numhask-bench: "Did not find executable at specified path"

### ISSUE THREAD

**Issue by Magalame** [tonyday567/numhask#132]
Running `stack build --exec "$(stack path --local-install-root)/bin/numhask-bench" --exec "$(stack path --local-bin)/pandoc -f markdown -i other/bench_.md -t markdown -o readme.md --filter pandoc-include --mathjax" --file-watch` 
It eventually fails with `Did not find executable at specified path: /home/user/Projects/numhask/.stack-work/install/x86_64-linux/nightly-2019-03-15/8.6.4/bin/numhask-bench`

**Comment by tonyday567** [comment]
The benchmarking relies on pandoc to produce the readme.md markdown file.  For the latter part of the command to work, you'll need to:

```
stack install pandoc
stack install pandoc-include
```
if you dont have pandoc installed.

**Comment by tonyday567** [comment]
Fixed in master with https://github.com/tonyday567/numhask/commit/19af1bd192855e1eaa0d9d8644377545fe10f3b1

**Comment by Magalame** [comment]
Seems like this might be more of an error with `pandoc-include`, but still: 
```
--  While building package pandoc-include-0.0.1 using:
      /home/nouey/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_2.4.0.1_ghc-8.6.4 --builddir=.stack-work/dist/x86_64-linux/Cabal-2.4.0.1 build --ghc-options " -ddump-hi -ddump-to-file -fdiagnostics-color=always"
    Process exited with code: ExitFailure 1
    Logs have been written to: /home/nouey/Projects/numhask/.stack-work/logs/pandoc-include-0.0.1.log

    Configuring pandoc-include-0.0.1...
    Warning: 'hs-source-dirs: src' directory does not exist.
    Preprocessing library for pandoc-include-0.0.1..
    Building library for pandoc-include-0.0.1..
    Preprocessing executable 'pandoc-include' for pandoc-include-0.0.1..
    Building executable 'pandoc-include' for pandoc-include-0.0.1..
    [1 of 1] Compiling Main             ( IncludeFilter.hs, .stack-work/dist/x86_64-linux/Cabal-2.4.0.1/build/pandoc-include/pandoc-include-tmp/Main.o )
    
    /tmp/stack8336/pandoc-include-0.0.1/IncludeFilter.hs:71:53: error:
        • Couldn't match type ‘[Char]’ with ‘Data.Text.Internal.Text’
          Expected type: Data.Text.Internal.Text
            Actual type: String
        • In the second argument of ‘readMarkdown’, namely ‘content’
          In the second argument of ‘($!)’, namely ‘readMarkdown def content’
          In the expression: return $! readMarkdown def content
       |
    71 | ioReadMarkdown content = return $! readMarkdown def content
       |                                                     ^^^^^^^
```

**Comment by tonyday567** [comment]
dunno. but pandoc-include is for post-processing, so results will be in the other directory.

**Comment by tonyday567** [comment]
https://github.com/steindani/pandoc-include/issues/15

This is the error. pandoc-include looks abandoned to me.

**Comment by Magalame** [comment]
Hmm, so there is no way to fix it? Since the benches rely on `pandoc-include`?

**Comment by tonyday567** [comment]
Just have to bump stack back on the resolver, so something like:

`stack install pandoc-install --resolver=lts-10.10`

**Comment by tonyday567** [comment]
The better solution is to wrap pandoc and pandoc-include inside the existing report production code, but then the bug in pandoc-include hardens, as it's tough to patch an abandoned library.

**Comment by tonyday567** [comment]
Had to rewind a bit furher.

`stack install pandoc-include --resolver=lts-8.9` worked for me.
