### ISSUE TITLE
cabal-version 3.0 not supported by Stackage curator

### ISSUE THREAD

**Issue by jkachmar** [tonyday567/numhask#141]
It looks like the `numhask-0.5` version bump (along with related dependencies) included `*.cabal` using the new `cabal-version: 3.0` syntax.

Unfortunately the Stackage curator doesn't yet support this, and I've had to drop `numhask-0.5` from the nightly builds.

I just did a quick check locally, and it seems like all of the projects here work just fine with `cabal-version: 2.4` syntax; would you be willing to accept a PR that makes this change?

(cf. commercialhaskell/stackage#5382)

**Comment by tonyday567** [comment]
Thanks for the report.

In the PR you suggested, I have two red flags for the `cabal v2-build all` on travis.

Cabal 2.4 does not support ghc-8.8.3
---

```
Warning: Unknown/unsupported 'ghc' version detected (Cabal 2.4.1.0 supports
'ghc' version < 8.7): /opt/ghc/8.8.3/bin/ghc is version 8.8.3
```

This warning was why I bumped up to cabal-version 3.0. It wigs me out to ignore this very clear message that Cabal 2.4.1.0 + ghc-8.8.3 is unsupported.

Down-bumps of Cabal are needed everywhere
---

```
cabal: Could not resolve dependencies:
[__0] trying: numhask-hedgehog-0.4.0 (user goal)
[__1] next goal: numhask-space (dependency of numhask-hedgehog)
[__1] rejecting: numhask-space-0.4.0 (unsupported spec-version 3.0)
```

So, I need to bump down cabal for numhask-space as well (not on stackage), or ignore that `cabal v2-build all` errors.

I have, of course, in a fit of retrospective insanity, decided to make numhask-0.5 a breaking change, bumped about 10 upstream libraries to >=numhask-0.5 & cabal-version 3.0, bumped version numbers, and uploaded them to hackage.

Libraries will now start to fail on `stack build --resolver nightly`, I presume, with lts failure soon to follow.

Any advice?

**Comment by jkachmar** [comment]
I didn't communicate myself as well as I'd intended to. Any version of `cabal-install` is fine (and, indeed `cabal-install-3.0.0.0` and up are great!) but what the Stackage curator tool has trouble with at the moment is handling `cabal-version: 3.0` (i.e. the specification that governs the `*.cabal` file format).

Since none `numhask`'s projects are using features from the latest file spec, it seemed like it'd be a quick fix.

**Comment by tonyday567** [comment]
oh, there's a difference between cabal-install and cabal-version. Cool, thanks!
