### ISSUE TITLE
Separate typeclass for L¹ distance?

### ISSUE THREAD

**Issue by sashaboyd** [tonyday567/numhask#144]
Hi there, thanks for all your work on NumHask, I'm really liking it.

Lately I've been writing some code involving board games—with discrete squares—so the L¹ distance makes sense, but L² distance etc. doesn't. I was wondering if maybe there could be a separate typeclass for L¹ distance that would work with integral Pairs for example—if that fits with the library's design goals, of course. At the moment I'm just throwing an exception for normL2 and distanceL2. Thanks!

**Comment by LeanderK** [comment]
I have some code laying around where i used type-classes to encode the different metrics and norms, which I think is the right approach. I personally would also need other norms (e.g. inf.-norm and matrix-norms).

**Comment by tonyday567** [comment]
L2 is easy to code separately and is a wart.

I'm getting close to a 0.1.0 major release, and breaking change ideas are welcome.

**Comment by tonyday567** [comment]
#146 closes.  I meant a 0.6 release

**Comment by sashaboyd** [comment]
Cool, thanks!

**Comment by tonyday567** [comment]
Any chance for a peek at the code would be great. 

I renamed normL1 to norm and distanceL1 to distance

**Comment by LeanderK** [comment]
I have exams until middle of august, then i have time. I would be interested in reviving `Numhask`! I don't know if you remember, i made a proposal to encode the basics via newtypes, i would be interested in reviving this idea. I have thought a bit on how to improve the library, but I am very busy right now.

**Comment by LeanderK** [comment]
I had a seperate library encoding linear-algebra aspects based on the newtype-version. I can dig it up when i find the time.

**Comment by tonyday567** [comment]
numhask-space does a pretty good job of getting a grid from a space. It has a "sensible" grid that rounds like they do in chart creation, coming up with sensible labels and such. It's not tied to numhask in any way - misnamed at the start!
