### ISSUE TITLE
Rename `size` to `norm2`

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#20]
For scalars there is no issue (`size == abs`), but for elements of a vector space it is unclear which norm we are referring to.
I would opt to rename `size` to `norm2` to make it clear we are defaulting to the L_2 norm, and have auxiliary functions for the general L_p norm.

**Comment by tonyday567** [comment]
sure

**Comment by tonyday567** [comment]
Alternative would be `normL2` which increases clarity?  

Adding a specific `normL1` and then `normLp` defined for p > 0 right?

wrt the Metric class: https://github.com/tonyday567/numhask/blob/master/numhask/src/NumHask/Algebra/Metric.hs#L88

Should `distance` also say `distanceL2` or is the sense of distance pretty much always reliably `normL2 (a - b)`?

**Comment by ocramz** [comment]
`normL2`, `normLp` etc are good : )

Also, no there are very interesting cases in which the distance between two objects is not given by the Euclidean norm:

https://en.wikipedia.org/wiki/Metric_(mathematics)#Examples

**Comment by tonyday567** [comment]
#24
