### ISSUE TITLE
numhask-accelerate

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#21]
A package for lifted functions that return in the `Acc` or `Exp` monad, in the spirit of `linear-accelerate` : https://hackage.haskell.org/package/linear-accelerate

**Comment by tonyday567** [comment]
numhask-accelerate has been on hold awaiting the numhask reorg that just PRed.  Next step is cleaning up numhask-array, doing some learnings about arrays using simpler containers before wading into the world of accelerate.

**Comment by tonyday567** [comment]
reducing scope
