### ISSUE TITLE
How do you write a new backend for numhask?

### ISSUE THREAD

**Issue by stites** [tonyday567/numhask#28]
I'm looking to write a numhask backend for the torch bindings I've been developing. Is numhask-array the place to go about this?

**Comment by tonyday567** [comment]
Yes.  However,

- numhask-array is stuck in this no man's land between dimensions usage and a roll-your-own singletons style.
- hasktorch tracks size via dimensions right?  as does a NumHask.Array.Array, and I'm not sure how to deal with this.

I'll take a closer look and hopefully get some answers.

**Comment by stites** [comment]
Yeah, I've seen the dimensions-singletons mix in some hasktorch, I think we lean on dimensions for the containers and singletons for Nats. We've got some `type KnownNatDimI` constraints to help out as well (I can try to dig up some examples if that would be helpful, as well).

Hasktorch has two flavors: dynamic and static (which is just a newtype around dynamic). So if passing dimensions around gets tough, i can make sure to write everything against Dynamic. I think it will still require a GADT, however, because torch (and thus hasktorch via backpack) only supplies monomorphic containers. There would have to be a layer of indirection to make a generic "torch tensor type" that, I think, numhask-array needs.

**Comment by tonyday567** [comment]
Short answer: no

Long answer:

The operators in the Container class https://github.com/tonyday567/numhask/blob/master/numhask-array/src/NumHask/Array.hs#L98 were the minimum ones necessary to make the container portion of the Array class polymorphic in container and able to supply the matrix operators we happened to have in numhask-array.  Most of the operators are, in turn, what was needed to get a Representable Functor instance for an Array, and this powers most of the numhask class hierarchy.

Beyond this, mapAlong, foldAlong, slice and friends are example operators that we guess are fundamental to tensor operations but have yet to be placed in any sort of lawful system of superclasses (hence cementing their fundamentalness).

So it's a mess.  A concrete aim is to get a matrix multiplication happening within the api - an instance of TensorProduct happening, and use this to hook into something like numhask-bench for performance testing.
