### ISSUE TITLE
Introduce convenience typeclasses

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#29]
In order to reduce the constraints noise, we might want to define "wrapper" typeclasses of the form:

```
class (Eq a, Ord a, Show a) => Type a 
instance (Eq a, Ord a, Show a) => Type a
```

I'm thinking that `Num` could be redefined in terms of NumHask classes (`FromInteger`, `AdditiveGroup`, `MultiplicativeGroup` ... ? ). Would this facilitate the adoption of NumHask?

**Comment by tonyday567** [comment]
I'm hoping -XDerivingVia comes along and makes usage a lot easier.

from a [reddit comment](https://www.reddit.com/r/haskell/comments/3z0ukd/reflecting_on_haskells_2015_and_my_wishes_for_2016/cyjt7cb/?context=3): There are pretty real pain points in determining how many intermediate steps to use, and the fact that you don't get to use laws gained in a subclass to reduce the number of definitions you have to supply in superclasses in Haskell.

Hence the decision to not replace or redefine Num in any way.  We could supply a `Num'` as you suggest, and it would be useful if an ecosystem sprung up around numhask, but you still have to supply definitions for all those sub-classes.

No easy fix that I can see.

**Comment by tonyday567** [comment]
Nope.
