### ISSUE TITLE
How to deal with integer literals?

### ISSUE THREAD

**Issue by ocramz** [tonyday567/numhask#30]
Every time I use a constant like `2`, the `Num` constraint appears even though I have explicitly hidden it from the imports.

**Comment by tonyday567** [comment]
https://www.haskell.org/onlinereport/basic.html#numeric-literals

**Comment by tonyday567** [comment]
So try also hiding `fromInteger` and `fromRational`.

It is also interacting with default declarations:

https://www.haskell.org/onlinereport/decls.html#default-decls

"In situations where an ambiguous type is discovered, an ambiguous type variable, v, is defaultable if:

v appears only in constraints of the form C v, where C is a class, and
at least one of these classes is a numeric class, (that is, Num or a subclass of Num), and
all of these classes are defined in the Prelude or a standard library (Figures 6.2--6.3, pages -- show the numeric classes, and Figure 6.1, page , shows the classes defined in the Prelude.)"

I haven't followed this particular rabbit hole very far, but the feel is that Num is baked right in to Haskell98, and unbaking might be difficult.

It would be fun to get a posse together, and go hunt this down inside GHC.  If it is baked in to Haskell98, we'd need a new language extension.

**Comment by ocramz** [comment]
Thanks!

**Comment by tonyday567** [comment]
Ok, my eyes always glazed over RebindableSyntax, but it's the beast we need.  Just need to write a fromRational ...

**Comment by tonyday567** [comment]
#39 included fromRational and added rebindableSyntax note to numhask-prelude examples
