### ISSUE TITLE
How to represent a "strictly positive floating" type

### ISSUE THREAD

**Issue by stites** [tonyday567/numhask#34]
I've often come across a need to write something like the following to account for "strictly positive floating types." 

```
newtype Pos a = Pos { getPos :: a }
mkPos :: Num a => a -> Maybe a 
```

Would this be possible to enforce with the constraints numhask provides? Maybe with a `NumHask.Algebra.Field.BoundedField`?

**Comment by tonyday567** [comment]
It can't be an ArithmeticGroup right?

We could have a `negate :: (FloatPos a, Float b) => a -> b`?  But can't call it `negate` given the difference between domain and codomain.  That roadblock seems to happen all the time with this hierarchy.  At one stage I started specifying some of the classes with separate domain and codomain types but instances go exponential quite quickly. 

So we would then have a BoundedRing, not a BoundedField, which is easy to add.  Or maybe not ... MultiplicativeGroup is lawful, so we have something between a Ring and a Field.  The tree grows!

**Comment by tonyday567** [comment]
#37 closes
