### ISSUE TITLE
distance for Word8 etc

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#46]
Word8 addition cycles, eg `127 + 1 = -128`.  Is this correct `distancep1 127 (-128) == 1`?

And also what is the most common computation?  Is it this: https://stackoverflow.com/questions/22445019/fast-branchless-unsigned-int-absolute-difference/22459071

**Comment by ocramz** [comment]
Uh, let's leave assembly-level optimizations as a last thing : D . `Word8` and friends are finite fields, so I guess we need an additional typeclass for this? https://en.wikipedia.org/wiki/Finite_field#Relationship_to_other_commutative_ring_classes

**Comment by ocramz** [comment]
BTW, this is related to #81
