### ISSUE TITLE
NumHask.Complex

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#47]
adding the additive instances for Complex meant adding NumHask.Algebra.Additive as an import for NumHask.Algebra.Multiplicative.  This dependency pollution will likely create problems down the track and prevent innovation due to cyclicality of imports.

Should we roll our own NumHask.Complex?

**Comment by ocramz** [comment]
Well, Complex numbers using lots of memory have been a long-standing issue. Perhaps this could be the time to roll a set of unpacked complex number types?
