### ISSUE TITLE
base Num instances

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#49]
Include instances for:

- [x] Sum
- [x] Product
- [ ] Down
- [ ] Identity
- [ ] Max
- [ ] Min
- [ ] Fixed
- [ ] Alt
- [ ] Const

which are all base Num instances.

**Comment by ocramz** [comment]
* `Data.Semigroup` :

  * Sum : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Semigroup.html#t:Sum

  * Product : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Semigroup.html#t:Product

  * Max : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Semigroup.html#t:Max

  * Min : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Semigroup.html#t:Min

* `Data.Monoid`

  * Alt : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Monoid.html#t:Alt

* `Data.Ord`

  * Down : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Ord.html#t:Down

* `Data.Functor` :

  * Identity: http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Functor-Identity.html#t:Identity 

  * Const: http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Functor-Const.html#t:Const 

* `Data.Fixed`

  * Fixed : http://hackage.haskell.org/package/base-4.11.1.0/docs/Data-Fixed.html#t:Fixed

**Comment by tonyday567** [comment]
I can see three ways to go with respect to `Sum` (and by extension the others listed):

1. re-implement `Sum` in numhask with an Additive constraint.

2. provide Num instances for numbers that are specified in numhask (Currently this is `Ratio a`), so they can use the Sum version in prelude.

3. ignore `Sum` and implement `sum` without going through the whole "monoid under addition" guff.  This is what is currently in there.

I personally favour re-implementing the full `Sum`

**Comment by ocramz** [comment]
I think Max and Min should wait until we have the partial order/semilattice typeclasses in place (#57 )

**Comment by ocramz** [comment]
@tonyday567 @LeanderK is this ticket still relevant?

**Comment by LeanderK** [comment]
I think so, I don't think the refactor has much impact on this ticket. It seems like a good first issue.

**Comment by ocramz** [comment]
@LeanderK Yes I had ported over `Sum` and `Product` but then I saw you extended / rewrote them :)

**Comment by LeanderK** [comment]
Ah, yeah. They are much more prominent now, being the basis for the whole `Ring`-Hierarchy.
I think this is a great initial issue to get started with numhask, it's clearly defined what to do and there's an inspiration in `base`. 
I don't think I have ever used the instances beside `Sum` and `Product`, so I would personally like to focus on other things first.

**Comment by tonyday567** [comment]
closed: reducing scope.
