### ISSUE TITLE
Ratio breakages

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#51]
round is wrong in the quotientField Ratio instance, and Ratio doesn't pass the UpperBoundedField and LowerBoundedFieldLaws.  I think the AdditiveMagma instance or/and reduce is where it's going wrong.

**Comment by LeanderK** [comment]
On it. Reduce is not at fault, it's the AdditiveMagma.
Not sure about round yet...

**Comment by LeanderK** [comment]
Ok, I think the bug for Round is not in Ration, but in Field.
https://github.com/tonyday567/numhask/blob/a2e3d556776ecb43cff4e60700430bcb6fe1dce5/numhask/src/NumHask/Algebra/Field.hs#L122
for `(1%2)` it returns `0` and should return `1`. Not sure why 😀. The implementation of `properFraction` is correct.

**Comment by tonyday567** [comment]
#67 fixes
