### ISSUE TITLE
Polymorphic Logic

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#57]
If #56 works out, the remaining friction between backprop and numhask are api spots that use Bool's.  At the moment, this is just the Epsilon class but I think having a Bool that can be lifted to be differentiable is pretty cool.

This, in turn, raises a lot of questions about stuff like Lattices that haven't been dealt with yet.

**Comment by ocramz** [comment]
You mean something like `Eq_` , `POrd_` , `Lattice`, `Bounded`, `Boolean` found in SubHask ?

**Comment by ocramz** [comment]
For the definition of Eq_ (generalized equality in which the result of the comparison is an open type family `Logic`) https://hackage.haskell.org/package/subhask-0.1.1.0/docs/SubHask-Algebra.html#t:Eq_

**Comment by tonyday567** [comment]
Yes, I think the subhask heirarchy is a great starting point, but way too ambitious.  We don't need need to rewrite and rewire actual Boolean and Ord instances, or create things like `instance Eq_ Double`.  Instead, the rough task would be:

- add Eq_, Ord_ (POrd_ looks good I suppose) and Lattice classes, with generalised (:==), (:>=) operators.
- `instance Eq_ Boolean where (:==) = (==)` etc
- invent some sort of fuzzy logic that can be lifted into a differential, so we can say True is that-a-way!

A bit hand-wavey I know but it would generalise a large class of optimisation constraints.

**Comment by tonyday567** [comment]
Closed: reducing scope.
