### ISSUE TITLE
Backend-Agnostic types

### ISSUE THREAD

**Issue by LeanderK** [tonyday567/numhask#68]
Just want to kick off the discussion.
When doing numerical calculations, we will have to deal with different backends (CPU/GPU etc.) and I would really like to support them as much as possible (ML needs a GPU for a lot of tasks).
Ideally, the computation and the representation would be 2 different things.
Right now, most of the types don't care what the representation is, but some are defined in Haskell (like `Complex`, which I am interested in).
I also think `Complex`, as defined today, would not be suitable to performant numerical calculations, since Haskell can't unpack the two elements.
I don't have more examples (haven't searched much), but I would be interested in the general stance of this library.

**Comment by tonyday567** [comment]
Totally.  For a long time, I've been aiming for accelerate instances, but I ran into serious friction between the way I saw n-dimensional arrays and the way accelerate represents them.  Specifically, I was assuming we could rely on Functor-style (ie Boxed) functionality for containers but that goes against the computational environment of an accelerate.

So the ideal is that the library is a principled use of duct tape to help fit together all the various specialty libraries out there (all of which kind of assume a monolithic perspective that they are the only computational environment that matters).

How specialisation comes to be with respect to something like an unboxed array of complex numbers (pair of arrays or array of pairs?) is a very open question.  The answer is whatever the fastest way is that can still utilise the API.  Slightly longer answer might have to wait to see what backpack brings us.

**Comment by LeanderK** [comment]
Not an easy task...I wouldn't be too ambitious with `numhask`, otherwise you only create 'subhask` 😀
Also, I don't like these monolithic projects, I would try to clearly define what numhask should do and try to do it well, which I think are some basic building blocks to do high-performance numerical computations.

**Comment by tonyday567** [comment]
Defining numhask ambition is easy!  

Lawful replacements for Num, Fractional and Real, and support for higher-kinded numbers.

**Comment by tonyday567** [comment]
reducing scope
