### ISSUE TITLE
Hierarchy often unintuitive

### ISSUE THREAD

**Issue by LeanderK** [tonyday567/numhask#72]
I will update this ticket with more details later, trying out numhask for a project, but I think the hierarchy is often unintuitive. 
It just feels "off" when using it.

I think numhask would benefit from a refocus. My opinion right now is that numhask should strive for a numerical-hirarchy formed from basic abstract algebra and be mostly concerned with numbers. 
There are some things in this library where I don't really understand how they can fit. Bits and pieces from other math branches, linear algebra etc., or other stuff like in `NumHask.Algebra.Metric`, seemingly random in this library.

Some basic data-structures to help other libraries are fine imho, but I wouldn't try to be too much and fail at doing the original job (numbers and combining them) well.

I would:
- delete `Metric`, why is `Signed` even in there and what does `Normed` have to do with the library?
- `Rational` seems very out of place in `Algebra`, I would move it into `Data`.
- `Basis` is super confusing, it's not what you expect (Basis from linear algebra) and seems ad-hoc
- `Singleton` I am not sure what it does. 
- `Magma` classes have not the usual names, also I would reduce `Additive` and `Multiplicative`. For example: I don't think `AdditiveMagma` is a good idea, because I am not sure what this should mean, mathematically. I think we should only speak of something "Additive" when it matches some basic intuition that it adds something. A magma is only a closed operation.

**Comment by LeanderK** [comment]
Also: I am thinking about creating a linear-algebra library on top of `numhask`.

**Comment by LeanderK** [comment]
I might code up a proposal

**Comment by ocramz** [comment]
I generally like most of these proposal but I'd like Metric and Normed to stay. 

Perhaps we could rework them somehow, such as: 

* Adding a `Module` constraint on `Normed` (i.e. to signify that it's vector spaces that are normed):

     Module a => Normed a b

* Removing the Lebesgue norms in `Metric` (there are metrics that do not follow from a notion of Lp norm, such as distances on strings etc.)

* While we're at it we could add a `Divergence` class? These generalize metrics in various ways, for example both the L2 norm and the Kullback-Leibler divergence are examples of Bregman divergences (which are very used in convex analysis)

**Comment by LeanderK** [comment]
I would certainly rework them, if they stay. But Normed/Metric belong to measure-theoy, which I think is out of scope.
If they stay, I would like to separate the Measure-theory from the Algebraic structures and give each a proper folder.
Especially `Divergence`, being a generalization of statistical distance, would be weird to introduce without being able to speak about probability distributions. To really use it, you need to use some library which introduces probabilities, distributions etc. and I would argue that  `Divergence` belongs there rather than in this library.

**Comment by tonyday567** [comment]
The library started as an extraction of subhask classes, and then I winnowed down the constraints to just those that were needed for <.> and ><.  Normed is a superclass of Banach which was originally a super of Hilbert.  Beyond that, I haven't thought of the categories of math involved.

There's a lot to unpack in your comments:
- a Measure folder is a good idea and I'm open to dropping said folder if we're diverging to far from `number combinators`.
- yes, rational belongs in data
- Basis I stole from subhask.  What do you call element-by-element binary operator classes?
- Singleton is just something I needed at some stage which may well be refactored out elsewhere.
- Magma comments I don't understand. An AdditiveMagma is a magma that adds with an operator that is called `plus`.  Yes, it's only law is closure.  But, the laws for AdditiveUnital and AdditiveAssociative need a common binary operator defined elsewhere.  But very open to alternative constructs with a sound basis.  You might like to look at [gaia](https://github.com/SamuelSchlesinger/gaia), where I stole the magma names from.
- What would be the usual names?

A proposal sounds great, but happy to proceed with all the clean up stuff you suggest.

**Comment by LeanderK** [comment]
@tonyday567 thank's for the pointers to gaia! Quite clever with the `Coercible` Solution. What was the problem with `coerce` using it in practice?

**Comment by LeanderK** [comment]
My first try is at #75

**Comment by tonyday567** [comment]
I'm not sure what happened with Coercible.  The original author gave up on development and it was easier to duplicate Additive and Multiplicative than work out whether coerce was worthwhile.

**Comment by tonyday567** [comment]
Can we close given the new hierarchy?

**Comment by LeanderK** [comment]
closed! 🙂
