### ISSUE TITLE
Mutability

### ISSUE THREAD

**Issue by LeanderK** [tonyday567/numhask#73]
We are here for the speed and real-world applications and mutability is crucial for many algorithms.

I would like to have a "mirrored" hierarchy, that extends the immutable hirarchy with some mutable version of the basic functions.

**Comment by ocramz** [comment]
I don't think we need new typeclasses for this; adding functions that operate on mutable data with numhask operators should be enough.

**Comment by LeanderK** [comment]
but the signatures don't match?
I would like to have a mutable Int with, for example, `plusM :: m a -> a -> m ()`, so that I can add normal nubers to the mutable int.

**Comment by ocramz** [comment]
I don't think replicating functionality/typeclasses is a good idea. Say we have an action which returns an Int, `intm0 :: PrimMonad m => m Int`, and we want to double it, we can say `intm >>= pure . (* 2)`. That's the whole point of the pure/impure separation really.

**Comment by LeanderK** [comment]
Well, I am not sure. I think the convenience is well worth it, especially if the define the operators. Something like `+=`, which are common in other languages and should be immediately understood.

I am also not sure whether `intm >>= pure . (* 2)` is really enough. What about multiplying matrices, especially if they are bigger?

But in the end, I think the priority of this ticket is rather low. It was just an idea.

**Comment by tonyday567** [comment]
I like the idea of (+=), (*=) etc though others may choke.  This is, however, one of those things that doubles the workload of any basic refactor.  The subhask code base was absolutely polluted with mutable versioning.

**Comment by LeanderK** [comment]
I am closing this ticket...I don't think it's that important and was just an idea. Maybe later
