### ISSUE TITLE
Zero totalized fields

### ISSUE THREAD

**Issue by JamieBallingall** [tonyday567/numhask#74]
The definition of field currently reads:

``
class (AdditiveGroup a, MultiplicativeGroup a, Ring a) =>
Field a
``

which implies, among other things, that:

``
a * recip a = one
``

which isn't true if `a = zero`.

The standard answer is to make `recip` partial and leave `recip zero` undefined. I suspect that we want to avoid partial functions if at all possible.

The smallest change is perhaps to define `recip zero = zero` and require the law `a = zero || a * recip = one`.

A more extensive solution would be to introduce [regular semigroups](https://en.wikipedia.org/wiki/Regular_semigroup) and related structures like [Von Neumann regular rings](https://en.wikipedia.org/wiki/Von_Neumann_regular_ring) which have weak inverses (`winv`) that are total and satisfy:

``
a * (winv a) * a = a
``

and perhaps also

``
(winv a) * a * (winv a) = (winv a)
``

This class is strictly larger than the zero-totalized fields and so we would still specify those with `a = zero || a * winv a = one`.

I'm happy to write up a proposal for introducing all these new structures or try to create a pull request for the smaller change. I would need some guidance on what form proposals usually take.

**Comment by LeanderK** [comment]
I think a partial function will be unavoidable, since haskell's type-system is not expressible enough to state such a fact. And even if this would be possible to state, you would have to constantly prove to the typechecker that you don't feed 0s to `recip`.

**Comment by JamieBallingall** [comment]
Yes, I meant `a = zero || a * recip a = one`. Thank you.

Perhaps I have misunderstood the scope of this project but I didn't think many of these laws were stated in the type system.

I agree that the most principled usable system is the goal.

I agree that people are used to division by zero being undefined. Perhaps we can have:
`Field` with `recip :: Field -> Maybe Field`
`ZeroTotalizedField` with `winv :: ZeroTotalizedField -> ZeroTotalizedField`

**Comment by LeanderK** [comment]
a safe-version would be great, I think! But I would provide it as an alternative, with a note that we don't have a great solution yet for zero.

I am currently working on a proposal, which overhauls the hirarchy:
https://github.com/tonyday567/numhask/pull/75
Maybe we can join forces?

**Comment by tonyday567** [comment]
@JamieBallingall, thanks for your thoughts.

The zero guard is included in the actual Laws for MultiplicativeGroup which you can find [here](https://github.com/tonyday567/numhask/blob/master/numhask-test/src/NumHask/Laws.hs#L200).

An UpperBoundedField instance gets you `recip zero == infinity` which is the current mechanism to make recip total.  Whether infinity is a divide by zero error is left to the user, but we have laws at least.
We could make some sort of UpperBoundField Integer instance right now and divide by zero goes away, but this would be a different Integer to that in base, something like `data Integer' = Infinity | Integer' Integer`.  That's the start of a logic chain that ends up with something like the following being defined:

`data GuardedNum a = Zero | One | Infinity | NaN | UnguardedNum a | Singleton a | Diagonal a etc etc`

and then you get to invent all sorts of computational shortcuts and short-circuits based on the algebraic rules.  It could work very nicely for higher-kinded numbers.

The current `recip` is a drop-in replacement for the Prelude `recip`,, no wriggle room there - we can't change the codomain to a Maybe.  But I like the sound of a ZeroField class (I think we could drop the Totalized adjective), it's very clear what is being supplied. 

A PR with the ZeroField class idea would be great, with some haddock docs and inclusion in NumHask.Laws is ideal.

**Comment by JamieBallingall** [comment]
Sounds good. I'll work on that PR and maybe make a few small tweaks to some of the comments. I think the comments above the `Field` class definition led me astray:
https://github.com/tonyday567/numhask/blob/eb52cf135027995c58c95136180f520fbdfa8683/numhask/src/NumHask/Algebra/Field.hs#L59-L62
but it serves me right for reading the comments.

Closing for now so this doesn't clutter the place up.
