### ISSUE TITLE
move instances for prelude

### ISSUE THREAD

**Issue by LeanderK** [tonyday567/numhask#77]
I know everyone hates orphan-instances, but I think the abundance of instances we have to define makes the code really unreadable. I would like to move it to a different module.

I think orphan instances should be avoided, but I don't think it's that bad, because most of the instances are obvious, also we would export them as a default.

**Comment by tonyday567** [comment]
Instance pollution is a pain in maintaining the code, but orphans are just not tolerated in production code, or tolerable in most cases.  Yes, it makes reading the raw code difficult, but every core library has the same problem.

If ever the library has like, actual real users, then the main api is hackage and haddock comments, where instances are benign.

Appreciate instance boiler-plate destroys the beauty.  It's a tragedy but -1 from me.

**Comment by LeanderK** [comment]
totally understand it!
