### ISSUE TITLE
haddock laws

### ISSUE THREAD

**Issue by tonyday567** [tonyday567/numhask#78]
#74 highlights how the disconnection between a haddock stating a law, and an actual law, leads to bugs.

Is there anything to be done to close that gap?  refinement types? liquid haskell?

At the very least, an audit and fixup of all laws in the haddocks would be very appreciated.

**Comment by ocramz** [comment]
What if we introduce doctests everywhere?

**Comment by LeanderK** [comment]
but doctests on what? Int?
